### PR TITLE
Task: Log binary not found exception

### PR DESCRIPTION
**Pull request by revoltek-daniel**
Log binary not found exception cause Exception gets caught silently and message in log is something like:
> Uploaded file could not be moved! Write-permission problem in "folderName"?

### CODE REVIEW

**Comment by christophlehmann** [comment]
You get an exception when your configured binary is not found. Why should we log it?

**Comment by revoltek-daniel** [comment]
Because if you upload a file and the binary is not found, the exception get caught in 
typo3/sysext/core/Classes/Utility/File/ExtendedFileUtility.php:1118 and the Exception Message "Uploaded file could not be moved! Write-permission problem in "%s"?" will be logged.

**Comment by christophlehmann** [comment]
Okay, got it.

Relates: #24 #25

**Comment by christophlehmann** [comment]
Should be fine now in v1.1.0

**Pull request closed without merging**
